name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure gcc
      run: sudo apt install build-essential
    - name: install flex
      run: sudo apt install flex
    - name: configure
      run: sudo bash ./configure
    - name: make
      run: sudo make
    - name: make check
      run: sudo make check
    - name: make distcheck
      run: make distcheck
